account_app/urls.py
from django.urls import path
from. import views

app_name = 'account_app'
urlpatterns =[
    path('register/',views.registerform,name='register'),
    path('login/',views.loginform,name='login'),
    path('logout/',views.logoutform,name='logout'),
    path('profile/',views.profileform,name='profile'),
    path('update_user_profile/', views.updateuserprofile, name='update_user_profile'),
]

blog_app/urls.py
from django.urls import path
from .import views


app_name = 'blog_app'
urlpatterns =[
    path('cats_list/', views.cats_list, name='cats_list'),
    path('posts_to_cat/<int:cat_id>/', views.posts_to_cat, name='posts_to_cat'),
    path('posts_to_cat/<int:cat_id>/post_add/',views.post_add, name='post_add'),  
    path('posts_to_cat/<int:cat_id>/post_detail/<int:post_id>/',views.cat_post_detail, name='cat_post_detail'),
    path('posts_to_cat/<int:cat_id>/post_detail/<int:post_id>/update/',views.post_update, name='post_update'),
    path('posts_to_cat/<int:cat_id>/post_detail/<int:post_id>/delete-confirm/',views.post_delete_confirm, name='post_delete_confirm'),
    path('posts_to_cat/<int:cat_id>/post_detail/<int:post_id>/delete/',views.post_delete, name='post_delete'),

    #path('cat_add/', views.cats_add, name='cat_add'),#not need
    # path('cat_detail/<slug:cat_id>/', views.cat_detail, name='cat_detail'), #not need
    # path('all_posts_list/', views.all_posts_list, name='all_posts_list'),#not need
]

pages_app/urls.py
from django.urls import path,include
from . import views

app_name = 'pages_app'
urlpatterns = [
    path('',views.index, name ='index'),
    path('about/', views.about, name='about'),
    path('commerical/', views.commerical, name='commerical'),
    path('gallery/', views.gallery, name='gallery'),
    path('service/', views.service, name='service'),
    path('contact/', views.contactus, name='contactus'),
    path('success_contactus/', views.success_contactus, name='success_contactus'),
    path('under_construction/', views.under_construction, name='under_construction')
]

site_proj/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('pages_app.urls')),
    path('', include('blog_app.urls')),
    path('',include('account_app.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages_app/models.py
from django.db import models

# Create your models here.

pages_app/forms.py
from django import forms


class ContactUsForm(forms.Form):
    subject = forms.CharField(
        label='الموضوع',
        max_length=100,
        required=True,
        disabled=False)


    from_email = forms.EmailField(
        max_length=200,
        label='البريد الألكتروني للمرسل',
        required=True)


    message = forms.CharField(
        label='الرسالة النصية',
        required=True,
        max_length=4000,
        help_text='لا تستخدم الرموز أو الأرقام أو الوجوه التعبيرية.',
        widget=forms.Textarea(attrs={'placeholder': 'إكتب رسالتك هنا'}))






    # this field not work
    # full_name = forms.CharField(
    #     max_length= 100,
    #     label=' sender Full Name',
    #     required=True)



    # this field not work
    # Mobile_num = forms.CharField(
    #     initial='00966*********',
    #     max_length=14,
    #     label='sender Mobile(WhatsApp) Number',
    #    required=True)


    
    
   
    

pages_app/views.py
from django.contrib import messages
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.core.mail import send_mail, BadHeaderError
from django.shortcuts import render
from.forms import ContactUsForm

# Create your views here.
def index( request):
    return render(request,'pages_app/index.html')


def about(request):
    return render(request, 'pages_app/about.html')

def commerical(request):
    return render(request, 'pages_app/commerical.html')

def gallery(request):
    return render(request, 'pages_app/gallery.html')


def service(request):
    return render(request, 'pages_app/service.html')




def contactus(request):
    if request.method == 'POST':
        form = ContactUsForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            subject = cd["subject"]
            # print(subject)
            message = cd["message"]
            # print(message)
            from_email = cd["from_email"]
            msg_sender = str(message) + " " + str(from_email)
            message = msg_sender
            # print(from_email)
            recipient_list = ["developer.web.dj@gmail.com"]
            send_mail(subject,message,from_email,recipient_list,fail_silently=False)
        
            # You might want to add a success message or redirect to a thank you page
            messages.success(request,f'Thank you, your message sent successfully to us.')
            return redirect('pages_app:index')
    else:
        form = ContactUsForm()

    context = {
        'title': 'Contact Us',
        'form' : form,
    }
    return render(request, 'pages_app/contactus.html', context)





def success_contactus(request):
    return render(request, 'pages_app/contactus.html')
    # return HttpResponse('Success! Thank you for your message.')


def under_construction(request):
    return render(request, 'pages_app/under_construction.html')
   


# from book 
# def contactView(request):
#     if request.method == 'GET':
#         form = ContactForm()
#     else:
#         form = ContactForm(request.POST)
#         if form.is_valid():
#             subject = form.cleaned_data['subject']
#             from_email = form.cleaned_data['from_email']
#             message = form.cleaned_data['message']
#             try:
#                 send_mail(subject, message, from_email, ['admin@example.com'])
#             except BadHeaderError:
#                 return HttpResponse('Invalid header found.')
#             return redirect('success')
#     return render(request, "email.html", {'form': form})


# def successView(request):
#     return HttpResponse('Success! Thank you for your message.')

    
    

pages_app/templates/base.html
{% load static %}
<!doctype html>
<html lang="ar">

<!-- Head start -->

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link rel="stylesheet" href="{% static 'css/mystyles.css' %}">
    <link rel="stylesheet" href="{% static 'css/stylish-portfolio.css' %}">


    <link rel="icon" type="image/x-icon" href="{% static 'images/favicon.ico' %}">
    <title>The lawyer - Personal business website</title>
</head>
<!-- Head end -->


<!-- body start -->

<body id="page-top">
    <!--  header start (navbar + carousel + jumbotron) -->
    <!-- Navbar start -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" id="mainNav">

        <a class="navbar-brand js-scroll-trigger" href="#page-top">
            <span class="page-scroll">
             
                 <h5 style="font-size:6vw; text-shadow: 2px 2px 5px rgb(252, 152, 1);">المحامي</h5> 
            </span>
        </a>

        <button class="navbar-toggler navbar-toggler-right btn-sm my-button" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <i class="fas fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav text-uppercase  ml-auto">
                <li class="nav-item active"><a class="nav-link js-scroll-trigger" href="{% url 'pages_app:index' %}">الرئيسية</a></li>
                <li class="nav-item active"><a class="nav-link js-scroll-trigger" href="{% url 'pages_app:about' %}">تعرّف علينا</a></li>
                <li class="nav-item active"><a class="nav-link js-scroll-trigger" href="{% url 'blog_app:cats_list' %}">الإستشارات القانونية</a></li>
                <li class="nav-item active"><a class="nav-link js-scroll-trigger" href="{% url 'pages_app:contactus' %}">إتصل بنا</a></li>

                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                     الحساب
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        {%if user.is_authenticated %}
                        <a class="dropdown-item" href="{% url 'account_app:profile' %}">الملف الشخصي</a>
                        <a class="dropdown-item" href="{% url 'account_app:logout' %}">خروج</a> {%else%}
                        <a class="dropdown-item" href="{% url 'account_app:register' %}">تسجيل</a>
                        <a class="dropdown-item" href="{% url 'account_app:login' %}">دخول</a> {%endif%}
                    </div>
                </li>

                <li class="text-light font-italic">
                    <small>
                    {%if user.is_authenticated %}مرحبا<strong> {{user.username}}</strong> {%else %}
                    <span>مرحبا بالزائر</span>
                    {% endif %}
                    </small>
                </li>
            </ul>
        </div>

    </nav>
    <!-- Navbar end -->

    <!-- carousel start  -->
    <section id="my-carousel">
        <div id="carouselExampleCaptions" class="carousel slide pt-10" data-ride="carousel">
            <ol class="carousel-indicators">
                <li data-target="#carouselExampleCaptions" data-slide-to="0" class="active"></li>
                <li data-target="#carouselExampleCaptions" data-slide-to="1"></li>
            </ol>
            <div class="carousel-inner mt-50">
                <div class="carousel-item active">
                    <img src="{% static 'images/pages_app/slide_1.jpg' %}" alt="First slide" class="d-block w-100">
                    <div class="carousel-caption d-none d-md-block">
                        <!-- card start -->
                        <div class="card text-white bg-dark card-position bg-transparent1">
                            <div class="card-body">
                                <h5 class="card-title"> قوانين العمل معنا </h5>
                                <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                                <button class="btn btn-danger my-button " type="button"> المزيد <i class="fas fa-angle-double-left"></i></button>
                            </div>
                        </div>
                        <!-- card end -->
                    </div>
                </div>
                <div class="carousel-item">
                    <img src="{% static 'images/pages_app/slide_2.jpg' %}" alt="Second slide" class="d-block w-100">
                    <div class="carousel-caption d-none d-md-block">
                        <!-- card start -->
                        <div class="card card-position bg-transparent2">
                            <div class="card-body">
                                <h5 class="card-title"> العقود والمواثيق العامة </h5>
                                <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                                <button class="btn btn-danger my-button " type="button"> المزيد <i class="fas fa-angle-double-left"></i></button>
                            </div>
                        </div>
                        <!-- card end -->
                    </div>
                </div>
            </div>
            <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
        <!-- carousel end  -->
    </section>

    <!-- jumbotron start -->
    <section id="my-jumbotron">
        <div class="jumbotron jumbotron-fluid">
            <div class="container">
                <h1 class="display-4"> الخدمات القانونية</h1>
                <p class="lead">
                </p>
                تتشرف شركتنا بتقديم خدماتها لمجموعة من كبريات الشركات والمؤسسات المحلية والعالمية التي تعمل في مجال المقاولات وتقنية المعلومات والتأمين والتجارة العامة .
            </div>
        </div>
    </section>
    <!-- jumbotron end -->
    <!--  header end (navbar + carousel + jumbotron) -->


    <!--  dynamic content start  -->
    {% block content %} {% endblock content %}
    <!--  dynamic content end  -->



    <!--  footer  start -->
    <section id="footer">

        <footer class="bg_main">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md pt-4">
                        <div class="card-group">
                            <div class="card pt-1  mr-1 ml-1">
                                <h5 class="card-title text-center border-bottom pb-2 pt-2">ترخيص حكومي</h5>
                                <div class="card-body pt-0 pb-1">
                                    <p>محتوى عربي محتوى عربي محتوى عربي.</p>
                                </div>
                            </div>
                            <div class="card pt-1 mr-1 ml-1">
                                <h5 class="card-title text-center border-bottom pb-2 pt-2">قوانين هامة</h5>
                                <div class="card-body pt-0 pb-1">
                                    <ul>
                                        <li><a class="text-dark" href="#">وثائق مهمة</a></li>
                                        <li><a class="text-dark" href="#"> وثائق مهمة</a></li>
                                        <li><a class="text-dark" href="#">وثائق مهمة</a></li>
                                    </ul>
                                </div>
                            </div>
                            <div class="card pt-1 mr-1 ml-1">
                                <h5 class="card-title text-center border-bottom pb-2 pt-2">وسائل التواصل الاجتماعي</h5>
                                <h4 class="card-body text-center pt-0 pb-1">
                                    <a class="text-secondary" href="#"><i class="fab fa-facebook"></i></a>
                                    <a class="text-secondary" href="#"><i class="fab fa-twitter"></i></a>
                                    <a class="text-secondary" href="#"><i class="fab fa-instagram"></i></a>
                                    <a class="text-secondary" href="#"><i class="fab fa-youtube"></i></a>
                                    <a class="text-secondary" href="#"><i class="fab fa-telegram"></i></a>
                                    <a class="text-secondary" href="#"><i class="fab fa-linkedin"></i></a>
                                </h4>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md text-center p-1">
                        <small class="text-light">&copy; جميع الحقوق محفوظة {% now 'Y' %}</small>
                    </div>
                </div>
            </div>
        </footer>

    </section>

    <!--  footer  end -->

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="{% static 'js/jquery-3.5.1.slim.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'js/fontawesome-all.min.js' %}"></script>
    <script src="{% static 'js/scripts.js' %}"></script>

    <!-- Option 2: jQuery, Popper.js, and Bootstrap JS
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
    -->
</body>
<!-- body end -->

</html>