account_app/urls.py
from django.urls import path
from. import views

app_name = 'account_app'
urlpatterns =[
    path('register/',views.registerform,name='register'),
    path('login/',views.loginform,name='login'),
    path('logout/',views.logoutform,name='logout'),
    path('profile/',views.profileform,name='profile'),
    path('update_user_profile/', views.updateuserprofile, name='update_user_profile'),
]

blog_app/urls.py
from django.urls import path
from .import views


app_name = 'blog_app'
urlpatterns =[
    path('cats_list/', views.cats_list, name='cats_list'),
    path('posts_to_cat/<int:cat_id>/', views.posts_to_cat, name='posts_to_cat'),
    path('posts_to_cat/<int:cat_id>/post_add/',views.post_add, name='post_add'),  
    path('posts_to_cat/<int:cat_id>/post_detail/<int:post_id>/',views.cat_post_detail, name='cat_post_detail'),
    path('posts_to_cat/<int:cat_id>/post_detail/<int:post_id>/update/',views.post_update, name='post_update'),
    path('posts_to_cat/<int:cat_id>/post_detail/<int:post_id>/delete-confirm/',views.post_delete_confirm, name='post_delete_confirm'),
    path('posts_to_cat/<int:cat_id>/post_detail/<int:post_id>/delete/',views.post_delete, name='post_delete'),

    #path('cat_add/', views.cats_add, name='cat_add'),#not need
    # path('cat_detail/<slug:cat_id>/', views.cat_detail, name='cat_detail'), #not need
    # path('all_posts_list/', views.all_posts_list, name='all_posts_list'),#not need
]

site_proj/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('pages_app.urls')),
    path('', include('blog_app.urls')),
    path('',include('account_app.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account_app/models.py
from blog_app.models import Comment
from django.contrib.auth.models import User, Group
from django.db import models
from django.contrib.auth.models import User

from django.db.models.signals import post_save
from PIL import Image

# ---- PROFILE MODEL ----#
class Profile(models.Model):
    user_key = models.OneToOneField(
        User,
        on_delete = models.CASCADE,
        related_name = 'profile_to_user')
    
    prof_image = models.ImageField(
        verbose_name='صورة شخصية',
        help_text='أختر صورة رمزية تمثلك',
        upload_to='prof_images/%Y/%m/%d/',
        default='default_user.png',
        null=True)

    prof_created = models.DateTimeField(
        verbose_name='تاريخ إنشاء الملف الشخصي',
        auto_now_add=True,
        auto_now=False,
        null=True)

    prof_updated = models.DateTimeField(
        verbose_name='تاريخ آخر تحديث للملف الشخصي',
        auto_now_add=False,
        auto_now=True,
        null=True)


    prof_mob = models.CharField(
        verbose_name='رقم الجوال',
        max_length=14,
        help_text='ضع رقم الجوال بالصيغة الدولية مثلا (جوال سعودي 00966501234567)',
        unique=True,
        blank=False,
        null=True)


    Gender_choices = [
        ('M', 'ذكر'),
        ('F', 'أنثى'),
    ]
    gender = models.CharField(
        verbose_name='الجنس',
        max_length=10,
        choices=Gender_choices,
        null=True,
        blank=True)

    def __str__(self):
            return f'الملف الشحصي ل {self.user_key.username}'


    #inside Profile class we put function to decresse image that user insert in the profile model: 
    def save(self, *args, **kwargs):
            super().save(*args, **kwargs)

            img = Image.open(self.prof_image.path)
            if img.width > 300 or img.height > 300:
                output_size = (300, 300)
                img.thumbnail(output_size)
                img.save(self.prof_image.path)



#### end of Profile model(class)   #####




# this function out side profile class >> inside models file
# ---------(out class function) to doing Signal --------------------------------------------------------------------------#
# do function to creating proile automatically when user create his account register ------

def create_profile(sender, **kwargs):
    if kwargs['created']:
        Profile.objects.create(user_key=kwargs['instance'])

# post_save to call the above function and connect it with sender :
post_save.connect(create_profile, sender=User)

# --------------------------------------------------------------------------------
#طريقة أحمد أبو عيسى __ بالضبط نفس طريقة محمود روؤف أعلاه ه  -- work ok ادناه

# def create_profile(sender, **kwarg):
#     if kwarg['created']:
#         Profile.objects.create(user=kwarg['instance'])

# post_save.connect(create_profile, sender=User)
# ----------------------------------------------------------

# -- 'طريقة محمد عيسى المشروع الجديد .. يعمل ملف خارجي به دالة تعمل  السكنال 

# def customer_create_profile(sender, instance, created, **kwargs):
#     if created:
#         group = Group.objects.get(name="customer")
#         instance.groups.add(group)

#         Customer.objects.create(
#             user=instance,
#             name=instance.username
#         )

#         print('Customer profile created ! ')


# post_save.connect(customer_create_profile, sender=User)

account_app/forms.py
from django.contrib.auth.models import User
from .models import Profile
from django import forms
from django.core.exceptions import ValidationError

# ----------register form ---------------------#
class RegisterForm(forms.ModelForm):
    username = forms.CharField(label='اسم المستخدم', max_length=100, required=True,help_text='لا يُسمح بالفراغات')
    first_name = forms.CharField(label='الإسم الأول', max_length=100, required=True)
    last_name  = forms.CharField(label='الإسم الأخير', max_length=100, required=False)
    email = forms.CharField(label='البريد الألكتروني', max_length=200, required=True)
    password1 = forms.CharField(label='مفتاح الدخول', min_length=8, required=True,help_text='إستخدم 8 وأكثر', widget=forms.PasswordInput())
    password2 = forms.CharField(label='تأكيد مفتاح الدخول', min_length=8,required=True, help_text='إستخدم 8 وأكثر', widget=forms.PasswordInput())
#----- to costumize the RegisterForm fields -----# 
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2')
# ------- to check that password2 equal password1 -----#
    def clean_password2(self):
        if  self.cleaned_data['password1']!= self.cleaned_data['password2']:
            ValidationError('password2', code='invalid password')
            # raise forms.ValidationError('خطأ ، مفتاح الدخول غير متطابق')
        return self.cleaned_data['password2']
# ------- to check that username (unique) not used before -----#
    def clean_username(self):
        if User.objects.filter(username = self.cleaned_data['username']).exists():
            ValidationError('username', code='invalid username')
            # raise forms.ValidationError('أدخل أسم آخر ، نأسف لايمكن تكرار إسم المستخدم،أسم المستخدم الذي أخترته موجود مسبقا')
        return self.cleaned_data['username']






# ----------login form ---------------------#
class LoginForm(forms.ModelForm):
    username = forms.CharField(label='أسم المستخدم', max_length=100, required=True)
    password = forms.CharField(label='مفتاح الدخول', min_length=8, required=True, widget=forms.PasswordInput())  

#----- to costumize the LoginForm fields -----#   
    class Meta:
        model = User
        fields = ['username','password']







#--- the next two update class forms will put in the same view fhunction __ and display in the same html form--

class UpdateUserForm(forms.ModelForm):
    first_name = forms.CharField(label='الإسم الأول', max_length=100, required=True)
    last_name  = forms.CharField(label='الإسم الأخير', max_length=100, required=False)
    # email = forms.CharField(label='Email', max_length=200, required=True, disabled=False)
    email = forms.CharField(label='البريد الألكتروني', max_length=200, required=True)
    
    class Meta:
        model = User
        #fields = ('_all_',) -- not work in one to one relationship !!
        fields = ['first_name','last_name','email']


class UpdateProfileForm(forms.ModelForm):
   
    class Meta:
        model = Profile
        #fields = ('_all_',)-- not work in one to one relationship !!
        fields = ['prof_image','prof_mob', 'gender']


#----------------------------------------------------------------------------

account_app/views.py
from django.shortcuts import render,redirect
from .forms import RegisterForm, LoginForm
from django.contrib import messages
from django.contrib.auth import authenticate, login ,logout
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from blog_app.models import Post
from .forms import UpdateUserForm, UpdateProfileForm
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage

# ------------- show register form --------#
def registerform(request):
    if request.method == 'POST':
        register_form = RegisterForm(request.POST)
        if register_form.is_valid():
                new_user= register_form.save(commit=False)
                password= register_form.cleaned_data['password1']
                username= register_form.cleaned_data['username']
                new_user.set_password(password)
                #new_user.password = password  #----wrong-- not work! 
                new_user.save()

                #-- to doing login automatically after register
                user = authenticate(username=username,password=password) # without(request)_only data
                login(request,user)
                #-----------
                messages.success(request,f'تهانينا  {user.username}  تم تسجيلك ودخولك للموقع بنجاح ')
                register_form = RegisterForm()
                return redirect('account_app:profile')
    else:
        register_form = RegisterForm()
    
    context ={
        'form' : register_form ,
    }
    return render(request, 'account_app/register.html', context)
    



# ------------- show login form --------#
def loginform(request):
    if request.method =='POST':
        login_form = LoginForm(request.POST)
        username = request.POST['username']
        password = request.POST['password']
        #print(username)-- work ok
        #print(password)-- work ok
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            login_form = LoginForm()
            messages.success(request, f'مرحبا {user.username}')
            return redirect('blog_app:cats_list')
        else:
            login_form = LoginForm()
            messages.warning(request,'هناك خطأ في أسم المستخدم أو مفتاح الدخول ، من فضلك حاول مرة أخرى .')
            
            context = {
                'form': login_form,
            }
            return render(request, 'account_app/login.html', context)
       
    else:
        login_form = LoginForm()

        context ={
            'form': login_form,
        }
        return render(request,'account_app/login.html', context)








# ------------- show logoutform --------#
def logoutform(request):
    logout(request)
    messages.info(request, 'مع السلامة ، ننتظر عودتك قريباً')
    return redirect('blog_app:cats_list')







# ------------- show profile form --------#
@login_required(login_url='account_app:login')

def profileform(request):
    posts_to_author = Post.objects.all().filter(post_author = request.user.id)
   
    #-- paginator --#
    paginator = Paginator(posts_to_author, 5)
    page = request.GET.get('page')
    try:
        posts_to_author = paginator.page(page)
    except PageNotAnInteger:
        posts_to_author = paginator.page(1)
    except EmptyPage:
        posts_to_author = paginator.page(paginator.num_page)
    
    context ={
        'page' : page ,
        'posts_to_author': posts_to_author ,
    }
    return render(request,'account_app/profile.html', context)
  






#   ----- update  (user form + profile form) at the same html form page ------# 
def updateuserprofile(request): 
    update_user_form = UpdateUserForm(instance= request.user)
    update_profile_form = UpdateProfileForm(instance= request.user.profile_to_user)
    
    if request.method == 'POST':
        update_user_form = UpdateUserForm(data= request.POST , instance= request.user)
        update_profile_form = UpdateProfileForm(request.POST, request.FILES, instance=request.user.profile_to_user)

        if update_user_form.is_valid and update_profile_form.is_valid :
            update_user_form.save()
            update_profile_form.save()
            messages.success(request,'تم تحديث الملف الشخصي بنجاح')
            return redirect('account_app:profile')
    
    else:
        update_user_form = UpdateUserForm(instance=request.user)
        update_profile_form = UpdateProfileForm(instance=request.user.profile_to_user)
    
    context ={
        'update_user_form': update_user_form ,
        'update_profile_form' : update_profile_form ,
    }
    return render(request,'account_app/update_user_profile.html',context)

account_app/templates/account_app/login.html
{% extends 'base.html' %} {% block content %} {% load crispy_forms_tags %}



<!--messges start -->
<section id="messages">
    <div class="container">
        {% if messages %} {% for message in messages %}
        <div class='alert alert-{{message.tags}}'>
            <strong>{{ message }}</strong>
        </div> {% endfor %} {% endif %}
    </div>
</section>
<!-- messages end -->





<section>
    <div class="container">

        <div class="post pb-5 mt-5 ">
            <h4 class="entry-title about-color"><i class="fas fa-sign-in-alt bg-warning"></i> بوابة الدخول</h4>
        </div>

        <!-- login form  -->
        <div class='row '>
            <div class='col-md-10'>
                <form method="POST" class="form-group">
                    {% csrf_token %}
                    <div>
                        {{form|crispy}}
                    </div>
                    <div>
                        <button type='submit' class="btn btn-sm btn-dark">
                        دخول
                        </button>
                    </div>
                </form>

                <ul class="float-right">
                    <li> إذا كنت لا تملك حساب ، يمكنك عمل <a href="{% url 'account_app:register' %}"><b>تسجيل</b></a></li>
                </ul>

            </div>
        </div>
    </div>
</section>






{% endblock %}

account_app/templates/account_app/profile.html
{% extends 'base.html' %} {% block content %}



<!--messges start -->
<section id="messages">
    <div class="container">
        {% if messages %} {% for message in messages %}
        <div class='alert alert-{{message.tags}}'>
            <strong>{{ message }}</strong>
        </div> {% endfor %} {% endif %}
    </div>
</section>
<!-- messages end -->


<div class="post pb-5 mt-5 ">
    <h4 class="entry-title about-color pr-3"><i class="far fa-address-card"></i> الملف الشخصي {{user.username}}</h4>
</div>





<section id="myprofile">
    <div class="container">
        <div class="row mt-0">

            <div class="col-md-4">
                <div class="mt-3">
                    <div class="text-center mt-1 mb-3 ">
                        <img src="{{user.profile_to_user.prof_image.url}}" alt="{{user.username}}" class="image-wrap img-fluid rounded-circle" width="150px" height="150px">
                    </div>
                </div>
            </div>

            <div class="col-md-8">
                <div>
                    <ul class="list-group">
                        <li class="list-group-item list-group-item-warning">
                            <strong>
                                المعلومات الشخصية
                           </strong>
                        </li>
                        <li class="list-group-item">إسم المستخدم : {{user.username}}</li>
                        <li class="list-group-item">الإسم الأول : {{user.first_name}}</li>
                        <li class="list-group-item">الإسم الأخير : {{user.last_name}}</li>
                        <li class="list-group-item">البريد الألكتروني : {{user.email}}</li>
                        <li class="list-group-item">رقم الجوال : {{user.profile_to_user.prof_mob}}</li>
                        <li class="list-group-item">الجنس: {{user.profile_to_user.gender}}</li>
                    </ul>
                </div>
            </div>

        </div>

        <div class="mt-0 mb-5">
            <a type="button" href="{% url 'account_app:update_user_profile' %}" class="btn btn-success btn-sm btn-block"><i class="fas fa-pen-fancy"></i>  تحرير الملف الشخصي   </a>
        </div>

</section>




<hr>

<div class="post text-center">
    <h5 class="entry-title about-color pr-3"> مواضيع {{user.username}}</h5>

</div>

<section id="pagination">
    <div class="container">
        {% include 'blog_app/pagination.html' with page=posts_to_author %}
    </div>
</section>



<article>
    <div class="container">
        <table class="table table-hover table-responsive">
            <thead class="table-warning">
                <tr>
                    <th scope="col">الموضوع</th>
                    <th scope="col">
                        <i class="far fa-calendar-plus"></i> تم النشر
                    </th>
                    <th scope="col">
                        <i class="far fa-calendar-check"></i> آخر تحديث
                    </th>
                    <th scope="col">
                        <li class="fa fa fa-eye ">
                    </th>
                    <th scope="col">
                        <i class="far fa-comments"></i>
                    </th>
                </tr>
            </thead>
            <tbody>
                {% for post in posts_to_author %}
                <tr>
                    <th scope="row"><a href="{% url 'blog_app:cat_post_detail' cat_id=post.cat_fk.id  post_id=post.id %}">{{ post.post_title }}</a></th>
                    <td>{{ post.post_created }}</td>
                    <td>{{post.post_updated }}</td>
                    <td>{{ post.post_views_counter }}</td>
                    <td>{{ post.comments_for_post_count }}</td>
                    {% empty %}
                    <div>
                        لا يوجد لديك مواضيع تابعة لك {{user.username }}


                        <a href="{% url 'blog_app:cats_list'%}">
                     إختر قسم رئيسي 
                     </a> . وأضف له موضع جديد {% endfor %}
                    </div>
                </tr>
            </tbody>
        </table>
    </div>
</article>



</div>








<section id="pagination">
    <div class="container">
        {% include 'blog_app/pagination.html' with page=posts_to_author %}
    </div>
</section>

{% endblock %}





<div class="container">
    <section>
        <h4>Personal Profile </h4>

        <br><br>





        <div class="panel panel-warning row" style="padding:20px;">
            <div class="col-xs-12 col-md-6">

                <div class="panel panel-warning">
                    <div class="panel-body">
                        <img width="150" height="150" style="object-position:center !important;" src="{{user.profile_to_user.prof_image.url}}" alt="author image">
                        <a class="btn btn-info" style="float:right;" href="{% url 'account_app:update_user_profile'  %}">update</a>
                    </div>

                    <div>

                    </div>
                </div>

            </div>

            <div class="col-xs-12 col-md-6">

                <ul class="list-group">
                    <li class="list-group-item list-group-item-danger"> personal information </li>
                    <li class="list-group-item">Usernam : {{user.username}}</li>
                    <li class="list-group-item">First Name : {{user.first_name}}</li>
                    <li class="list-group-item">Last Name : {{user.last_name}}</li>
                    <li class="list-group-item">Email : {{user.email}}</li>
                    <li class="list-group-item">Mobile Number : {{user.profile_to_user.prof_mob}}</li>
                    <li class="list-group-item">Gender: {{user.profile_to_user.gender}}</li>
                </ul>


                <br><br><br>
                <div>
                    <p><strong>your posts :</strong></p>
                    <div style="float:right;">
                        {% include 'blog_app/pagination.html' with page=posts_to_author %}
                    </div>
                    <br><br><br>


                    <ul class="list-group">
                        {% for post in posts_to_author %}
                        <li class="list-group-item list-group-item-danger"><a href="{% url 'blog_app:cat_post_detail' cat_id=post.cat_fk.id  post_id=post.id %}">post_title : {{ post.post_title }}</a></li>
                        <li class="list-group-item fa fa-calendar-o"> : {{ post.post_created }}</li>
                        <li class="list-group-item fa fa-calendar-check-o"> : {{post.post_updated }}</li>
                        <li class="list-group-item fa fa fa-eye "> : {{ post.post_views_counter }}</li>
                        <i class="far fa-comments"></i> : {{ post.comments_for_post_count }}</li>
                        <br><br> {% empty %}
                        <li class="list-group-item ">no post written by you {{user.username }}</li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
    </section>

    <br><br>
</div>

account_app/templates/account_app/register.html
{% extends 'base.html' %} {% block content %} {% load crispy_forms_tags %}



<!--messges start -->
<section id="messages">
    <div class="container">
        {% if messages %} {% for message in messages %}
        <div class='alert alert-{{message.tags}}'>
            <strong>{{ message }}</strong>
        </div> {% endfor %} {% endif %}
    </div>
</section>
<!-- messages end -->






<section>
    <div class="container">

        <div class="post pb-5 mt-5 ">
            <h4 class="entry-title about-color"><i class="fas fa-thumbtack bg-warning"></i> التسجيل</h4>
        </div>

        <!--register form  -->
        <div class='row '>
            <div class='col-md-10'>
                <form method="POST" class="form-group">
                    {% csrf_token %}
                    <div>
                        {{form|crispy}}
                    </div>
                    <div>
                        <button type='submit' class="btn btn-sm btn-dark">
                      تسجيل
                        </button>
                    </div>
                </form>

            </div>
        </div>
    </div>
</section>






{% endblock %}





















<div class="container">
    <section>
        <div>
            <h5>Register Here:</h5>
        </div>
        <!-- register form  -->
        <div class='row '>
            <div class='col-md-8'>
                <form method="POST" class="form-group">
                    {%csrf_token %}
                    <div>
                        {{form|crispy}}
                    </div>
                    <div><button type='submit ' class="btn btn-skin">Register</button></div>
                </form>
            </div>
        </div>

    </section>
</div>

account_app/templates/account_app/update_user_profile.html
{% extends 'base.html' %} {% block content %} {% load crispy_forms_tags %}



<section>
    <div class="container">

        <br><br><br>


        <div>
            <p>
                <ol class="breadcrumb">

                    <li><b><a href="{% url 'account_app:profile' %}">profile </a></b></li>
                    <li class="active"><b>{{user.username}}</b></li>
                </ol>
            </p>
        </div>

        <br>




        <div class="post pb-5 mt-5 ">
            <h4 class="entry-title about-color pr-3"><i class="far fa-address-card"></i> تحرير صفحة الملف الشخصي {{user.username}}</h4>
        </div>



        <br><br>
        <!-- add new post form  -->
        <div class='row '>
            <div class='col-md-4'>
                <img width="150" height="150" style="object-position:center !important;" src="{{user.profile_to_user.prof_image.url}}" alt="{{user.username}}">
            </div>

            <div class='col-md-8'>
                <form method="POST" enctype="multipart/form-data" class="form-group">
                    {%csrf_token %}
                    <div>
                        {{update_user_form|crispy}}
                    </div>
                    <div>
                        {{update_profile_form|crispy}}
                    </div>

                    <br>

                    <div><button type='submit' class="btn btn-success btn-sm">إضافة التعديل</button></div>
                </form>

                <br><br><br>

            </div>

        </div>


    </div>
</section>




{% endblock %}