blog_app/urls.py
from django.urls import path
from .import views


app_name = 'blog_app'
urlpatterns =[
    path('cats_list/', views.cats_list, name='cats_list'),
    path('posts_to_cat/<int:cat_id>/', views.posts_to_cat, name='posts_to_cat'),
    path('posts_to_cat/<int:cat_id>/post_add/',views.post_add, name='post_add'),  
    path('posts_to_cat/<int:cat_id>/post_detail/<int:post_id>/',views.cat_post_detail, name='cat_post_detail'),
    path('posts_to_cat/<int:cat_id>/post_detail/<int:post_id>/update/',views.post_update, name='post_update'),
    path('posts_to_cat/<int:cat_id>/post_detail/<int:post_id>/delete-confirm/',views.post_delete_confirm, name='post_delete_confirm'),
    path('posts_to_cat/<int:cat_id>/post_detail/<int:post_id>/delete/',views.post_delete, name='post_delete'),

    #path('cat_add/', views.cats_add, name='cat_add'),#not need
    # path('cat_detail/<slug:cat_id>/', views.cat_detail, name='cat_detail'), #not need
    # path('all_posts_list/', views.all_posts_list, name='all_posts_list'),#not need
]

pages_app/urls.py
from django.urls import path,include
from . import views

app_name = 'pages_app'
urlpatterns = [
    path('',views.index, name ='index'),
    path('about/', views.about, name='about'),
    path('commerical/', views.commerical, name='commerical'),
    path('gallery/', views.gallery, name='gallery'),
    path('service/', views.service, name='service'),
    path('contact/', views.contactus, name='contactus'),
    path('success_contactus/', views.success_contactus, name='success_contactus'),
    path('under_construction/', views.under_construction, name='under_construction')
]

site_proj/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('pages_app.urls')),
    path('', include('blog_app.urls')),
    path('',include('account_app.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages_app/models.py
from django.db import models

# Create your models here.

pages_app/forms.py
from django import forms


class ContactUsForm(forms.Form):
    subject = forms.CharField(
        label='الموضوع',
        max_length=100,
        required=True,
        disabled=False)


    from_email = forms.EmailField(
        max_length=200,
        label='البريد الألكتروني للمرسل',
        required=True)


    message = forms.CharField(
        label='الرسالة النصية',
        required=True,
        max_length=4000,
        help_text='لا تستخدم الرموز أو الأرقام أو الوجوه التعبيرية.',
        widget=forms.Textarea(attrs={'placeholder': 'إكتب رسالتك هنا'}))






    # this field not work
    # full_name = forms.CharField(
    #     max_length= 100,
    #     label=' sender Full Name',
    #     required=True)



    # this field not work
    # Mobile_num = forms.CharField(
    #     initial='00966*********',
    #     max_length=14,
    #     label='sender Mobile(WhatsApp) Number',
    #    required=True)


    
    
   
    

pages_app/views.py
from django.contrib import messages
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.core.mail import send_mail, BadHeaderError
from django.shortcuts import render
from.forms import ContactUsForm

# Create your views here.
def index( request):
    return render(request,'pages_app/index.html')


def about(request):
    return render(request, 'pages_app/about.html')

def commerical(request):
    return render(request, 'pages_app/commerical.html')

def gallery(request):
    return render(request, 'pages_app/gallery.html')


def service(request):
    return render(request, 'pages_app/service.html')




def contactus(request):
    if request.method == 'POST':
        form = ContactUsForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            subject = cd["subject"]
            # print(subject)
            message = cd["message"]
            # print(message)
            from_email = cd["from_email"]
            msg_sender = str(message) + " " + str(from_email)
            message = msg_sender
            # print(from_email)
            recipient_list = ["developer.web.dj@gmail.com"]
            send_mail(subject,message,from_email,recipient_list,fail_silently=False)
        
            # You might want to add a success message or redirect to a thank you page
            messages.success(request,f'Thank you, your message sent successfully to us.')
            return redirect('pages_app:index')
    else:
        form = ContactUsForm()

    context = {
        'title': 'Contact Us',
        'form' : form,
    }
    return render(request, 'pages_app/contactus.html', context)





def success_contactus(request):
    return render(request, 'pages_app/contactus.html')
    # return HttpResponse('Success! Thank you for your message.')


def under_construction(request):
    return render(request, 'pages_app/under_construction.html')
   


# from book 
# def contactView(request):
#     if request.method == 'GET':
#         form = ContactForm()
#     else:
#         form = ContactForm(request.POST)
#         if form.is_valid():
#             subject = form.cleaned_data['subject']
#             from_email = form.cleaned_data['from_email']
#             message = form.cleaned_data['message']
#             try:
#                 send_mail(subject, message, from_email, ['admin@example.com'])
#             except BadHeaderError:
#                 return HttpResponse('Invalid header found.')
#             return redirect('success')
#     return render(request, "email.html", {'form': form})


# def successView(request):
#     return HttpResponse('Success! Thank you for your message.')

    
    

pages_app/templates/pages_app/about.html
{% extends 'base.html' %} {% load static %} {% block content %}

<!-- /////////////////////////////////////////Content -->
<div id="page-content">

    <!-- ////////////Content Box -->
    <section class="box-content">
        <div class="container">
            <div class="post pt-5 pb-5 ">
                <div class="post pb-5 ">
                    <h2 class="entry-title about-color"><i class="fas fa-paperclip fa-1x"></i> تعرّف علينا </h2>
                </div>
                <div class="row">
                    <div class="col-md-4 col-sm-12 ">
                        <img src="{% static 'images/pages_app/about2.jpg' %}" class="img-responsive" alt="About">
                    </div>
                    <div class="col-md-8 col-sm-12 ">
                        <p>
                            المحاماة مهنة حرة تشارك السلطة القضائية في استظهار الحقائق لتحقيق العدل وتأكيد سيادة القانون، ويطلق على من يمارس مهنة المحاماة محامي أو مستشار قانوني. وهى مهنة قائمة على تقديم المساعدة للأشخاص الطبيعيين والاعتباريين في اقتضاء حقوقهم والمعاونة في العمل
                            وفقا للقوانين الشرعية المتبعة في كافة المجالات والدفاع عن حقوق الآخرين والتوعية القانونية للمواطنين بحقوقهم وواجباتهم. " </p>
                    </div>
                </div>
                <p>
                    المحاماة مهنة حرة تشارك السلطة القضائية في استظهار الحقائق لتحقيق العدل وتأكيد سيادة القانون، ويطلق على من يمارس مهنة المحاماة محامي أو مستشار قانوني. وهى مهنة قائمة على تقديم المساعدة للأشخاص الطبيعيين والاعتباريين في اقتضاء حقوقهم والمعاونة في العمل
                    وفقا للقوانين الشرعية المتبعة في كافة المجالات والدفاع عن حقوق الآخرين والتوعية القانونية للمواطنين بحقوقهم وواجباتهم. إن المحاماة مهنة كتمان السر والشرف فلا يحق لمن يعمل بها أن يفشي أسرار عملاؤه، فقد وثقوا به ووضعوا ثقتهم فيهِ، ويحكم
                    ممارسة مهنة المحاماة القانون. ولهذا لا يستطيع ان يُنكر أحد أن المحاماة لازمة من لزوميات العدالة، وضرورة من ضرورات تحقيقها، والعدالة كل كامل لا يتجزأ ولا يتقطع وإلا انهار وانعدم . "
                </p>
                <blockquote>
                    <p>المحاماة مهنة حرة تشارك السلطة القضائية في استظهار الحقائق لتحقيق العدل وتأكيد سيادة القانون،</p>
                </blockquote>
                <p>
                    يطلق على من يمارس مهنة المحاماة محامي أو مستشار قانوني. وهى مهنة قائمة على تقديم المساعدة للأشخاص الطبيعيين والاعتباريين في اقتضاء حقوقهم والمعاونة في العمل وفقا للقوانين الشرعية المتبعة في كافة المجالات والدفاع عن حقوق الآخرين والتوعية القانونية للمواطنين
                    بحقوقهم وواجباتهم. إن المحاماة مهنة كتمان السر والشرف فلا يحق لمن يعمل بها أن يفشي أسرار عملاؤه، فقد وثقوا به ووضعوا ثقتهم فيهِ
                </p>
                <h2 class="about-color"><i class="fas fa-paperclip"></i> سيرة ذاتية</h2>
                <p>
                    المحاماة مهنة حرة تشارك السلطة القضائية في استظهار الحقائق لتحقيق العدل وتأكيد سيادة القانون، ويطلق على من يمارس مهنة المحاماة محامي أو مستشار قانوني.
                </p>
                <h2 class="about-color"><i class="fas fa-paperclip"></i> مبادئنا</h2>
                <p>
                    المحاماة مهنة حرة تشارك السلطة القضائية في استظهار الحقائق لتحقيق العدل وتأكيد سيادة القانون، ويطلق على من يمارس مهنة المحاماة محامي أو مستشار قانوني.
                </p>
                <h2 class="about-color"><i class="fas fa-paperclip"></i> عملائنا</h2>
                <p>
                    المحاماة مهنة حرة تشارك السلطة القضائية في استظهار الحقائق لتحقيق العدل وتأكيد سيادة القانون، ويطلق على من يمارس مهنة المحاماة محامي أو مستشار قانوني.
                </p>
                <p>
                    المحاماة مهنة حرة تشارك السلطة القضائية في استظهار الحقائق لتحقيق العدل وتأكيد سيادة القانون، المحاماة مهنة حرة تشارك السلطة القضائية في استظهار الحقائق لتحقيق العدل وتأكيد سيادة القانون،ي.
                </p>
                <p class="about-color">
                    <strong>
                 يطلق على من يمارس مهنة المحاماة محامي أو مستشار قانوني
                </strong>
                </p>
                <p>
                    يطلق على من يمارس مهنة المحاماة محامي أو مستشار قانوني. وهى مهنة قائمة على تقديم المساعدة للأشخاص الطبيعيين والاعتباريين في اقتضاء حقوقهم والمعاونة في العمل وفقا للقوانين الشرعية المتبعة في كافة المجالات والدفاع عن حقوق الآخرين والتوعية القانونية للمواطنين
                    بحقوقهم وواجباتهم. إن المحاماة مهنة كتمان السر والشرف فلا يحق لمن يعمل بها أن يفشي أسرار عملاؤه، فقد وثقوا به ووضعوا ثقتهم فيهِ
                </p>
                <div class="note">
                    <ol>
                        <li>يطلق على من يمارس مهنة المحاماة محامي أو مستشار قانوني</li>
                        <li>يطلق على من يمارس مهنة المحاماة محامي أو مستشار قانوني</li>
                        <li>يطلق على من يمارس مهنة المحاماة محامي أو مستشار قانوني</li>
                    </ol>
                    <div class="clear"></div>
                </div>
                <p>
                    المحاماة مهنة حرة تشارك السلطة القضائية في استظهار الحقائق لتحقيق العدل وتأكيد سيادة القانون، ويطلق على من يمارس مهنة المحاماة محامي أو مستشار قانوني. وهى مهنة قائمة على تقديم المساعدة للأشخاص الطبيعيين والاعتباريين في اقتضاء حقوقهم والمعاونة في العمل
                    وفقا للقوانين الشرعية المتبعة في كافة المجالات والدفاع عن حقوق الآخرين والتوعية القانونية للمواطنين بحقوقهم وواجباتهم. "
                </p>
                <p>
                    المحاماة مهنة حرة تشارك السلطة القضائية في استظهار الحقائق لتحقيق العدل وتأكيد سيادة القانون،
                </p>
            </div>
        </div>
    </section>

</div>
{% endblock %}

pages_app/templates/pages_app/commerical.html
{% extends 'base.html' %} {% load static %} {% block content %}

<!-- /////////////////////////////////////////Content -->
<div id="page-content">

    <!-- ////////////Content Box -->
    <section class="box-content">
        <div class="container">
            <div class="post pt-5 pb-5 ">
                <div class="post pb-5 ">
                    <h2 class="entry-title about-color text-center"><i class="fas fa-paperclip fa-1x"></i> العقود التجارية</h2>
                </div>
                <div class="row">
                    <div class="col-md-4 col-sm-12 text-center">
                        <img src="{% static 'images/pages_app/service_1.jpg' %}" class="img-responsive" alt="About">
                    </div>
                    <div class="col-md-8 col-sm-12 ">
                        <br>
                        <p>
                            المحاماة مهنة حرة تشارك السلطة القضائية في استظهار الحقائق لتحقيق العدل وتأكيد سيادة القانون، ويطلق على من يمارس مهنة المحاماة محامي أو مستشار قانوني. وهى مهنة قائمة على تقديم المساعدة للأشخاص الطبيعيين والاعتباريين في اقتضاء حقوقهم والمعاونة في العمل
                            وفقا للقوانين الشرعية المتبعة في كافة المجالات والدفاع عن حقوق الآخرين والتوعية القانونية للمواطنين بحقوقهم وواجباتهم. " </p>
                    </div>
                </div>
                <p>
                    المحاماة مهنة حرة تشارك السلطة القضائية في استظهار الحقائق لتحقيق العدل وتأكيد سيادة القانون، ويطلق على من يمارس مهنة المحاماة محامي أو مستشار قانوني. وهى مهنة قائمة على تقديم المساعدة للأشخاص الطبيعيين والاعتباريين في اقتضاء حقوقهم والمعاونة في العمل
                    وفقا للقوانين الشرعية المتبعة في كافة المجالات والدفاع عن حقوق الآخرين والتوعية القانونية للمواطنين بحقوقهم وواجباتهم. إن المحاماة مهنة كتمان السر والشرف فلا يحق لمن يعمل بها أن يفشي أسرار عملاؤه، فقد وثقوا به ووضعوا ثقتهم فيهِ، ويحكم
                    ممارسة مهنة المحاماة القانون. ولهذا لا يستطيع ان يُنكر أحد أن المحاماة لازمة من لزوميات العدالة، وضرورة من ضرورات تحقيقها، والعدالة كل كامل لا يتجزأ ولا يتقطع وإلا انهار وانعدم . "
                </p>
                <blockquote>
                    <p>المحاماة مهنة حرة تشارك السلطة القضائية في استظهار الحقائق لتحقيق العدل وتأكيد سيادة القانون،</p>
                </blockquote>
                <p>
                    يطلق على من يمارس مهنة المحاماة محامي أو مستشار قانوني. وهى مهنة قائمة على تقديم المساعدة للأشخاص الطبيعيين والاعتباريين في اقتضاء حقوقهم والمعاونة في العمل وفقا للقوانين الشرعية المتبعة في كافة المجالات والدفاع عن حقوق الآخرين والتوعية القانونية للمواطنين
                    بحقوقهم وواجباتهم. إن المحاماة مهنة كتمان السر والشرف فلا يحق لمن يعمل بها أن يفشي أسرار عملاؤه، فقد وثقوا به ووضعوا ثقتهم فيهِ
                </p>
            </div>
        </div>
    </section>

</div>
{% endblock %}

pages_app/templates/pages_app/index.html
{% extends 'base.html' %} {% load static %}
<div>
    {% block content %}

    <!--messges -->
    {% if messages %} {% for message in messages %}
    <br><br><br><br><br><br>
    <div class='alert alert-{{message.tags}}'>
        <strong class= 'text-center'>{{ message }}</strong>
    </div> {% endfor %} {% endif %}
    <!--end messages -->




    <!-- description -->
    <section class="page-section" id="circles-section">
        <div class="container">
            <div class="text-center">
                <h2 class="section-heading text-uppercase">بماذا نتميز ؟</h2>
                <h3 class="section-subheading text-muted">لسنا الأفضل و لكننا مميزون</h3>
            </div>
            <div class="row text-center">
                <div class="col-md-4">
                    <span class="fa-stack fa-4x">
                            <i class="fas fa-circle fa-stack-2x text-primary"></i>
                            <i class="fas fa-laptop fa-stack-1x fa-inverse"></i>
                        </span>
                    <h4 class="my-3">خدمات ألكترونية</h4>
                    <p class="text-muted">متابعة ألكترونية تغنيك عن التردد على المكاتب.</p>
                </div>
                <div class="col-md-4">
                    <span class="fa-stack fa-4x">
                            <i class="fas fa-circle fa-stack-2x text-primary"></i>
                            <i class="fas fa-clock fa-stack-1x fa-inverse"></i>
                        </span>
                    <h4 class="my-3"> لا للمماطلة</h4>
                    <p class="text-muted">سرعة بأنجاز المهام الموكلة لنا .</p>
                </div>
                <div class="col-md-4">
                    <span class="fa-stack fa-4x">
                            <i class="fas fa-circle fa-stack-2x text-primary"></i>
                            <i class="fas fa-lock fa-stack-1x fa-inverse"></i>
                        </span>
                    <h4 class="my-3">الإعتمادية والثقة</h4>
                    <p class="text-muted">هدفنا خدمة العميل بكل مصداقية وشفافية.</p>
                </div>
            </div>
        </div>
    </section>




    <!-- Portfolio Grid-->
    <section class="page-section bg-light" id="portfolio">
        <div class="container">
            <div class="text-center">
                <h2 class="section-heading text-uppercase">خدماتنا</h2>
                <h3 class="section-subheading text-muted">نفخر بتقديم كافة الخدمات القضائية.</h3>
            </div>
            <div class="row">
                <div class="col-lg-4 col-sm-6 mb-4 text-center">
                    <div class="portfolio-item">
                        <a class="portfolio-link" data-toggle="modal" href="{% url 'pages_app:under_construction' %}">
                            <div class="portfolio-hover">
                                <div class="portfolio-hover-content"><i class="fab fa-centos fa-3x"></i></div>
                            </div>
                            <img width="100%" class="img-fluid" src="{% static 'images/pages_app/service_1.jpg' %}" alt="" />
                        </a>
                        <div class="portfolio-caption">
                            <a  href="{% url 'pages_app:commerical' %}" class="portfolio-caption-heading">العقود التجارية</a>
                            <div class="portfolio-caption-subheading text-muted">صياغة إحترافية للعقود التجارية</div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 col-sm-6 mb-4 text-center">
                    <div class="portfolio-item">
                        <a class="portfolio-link" data-toggle="modal" href="{% url 'pages_app:under_construction' %}">
                            <div class="portfolio-hover">
                                <div class="portfolio-hover-content"><i class="fab fa-centos fa-3x"></i></div>
                            </div>
                            <img width="100%" class="img-fluid" src="{% static 'images/pages_app/service_2.jpg' %}" alt="" />
                        </a>
                        <div class="portfolio-caption">
                            <div class="portfolio-caption-heading">التمثيل والترافع</div>
                            <div class="portfolio-caption-subheading text-muted">تمثيل العملاء في المحاكم و ديوان المظالم</div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 col-sm-6 mb-4 text-center">
                    <div class="portfolio-item">
                        <a class="portfolio-link" data-toggle="modal" href="{% url 'pages_app:under_construction' %}">
                            <div class="portfolio-hover">
                                <div class="portfolio-hover-content"><i class="fab fa-centos fa-3x"></i></div>
                            </div>
                            <img width="100%" class="img-fluid" src="{% static 'images/pages_app/service_3.jpg' %}" alt="" />
                        </a>
                        <div class="portfolio-caption">
                            <div class="portfolio-caption-heading">الإستشارات </div>
                            <div class="portfolio-caption-subheading text-muted">تقديم الإستشارات القانونية والشرعية</div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 col-sm-6 mb-4 mb-lg-0 text-center">
                    <div class="portfolio-item">
                        <a class="portfolio-link" data-toggle="modal" href="{% url 'pages_app:under_construction' %}">
                            <div class="portfolio-hover">
                                <div class="portfolio-hover-content"><i class="fab fa-centos fa-3x"></i></div>
                            </div>
                            <img width="100%" class="img-fluid" src="{% static 'images/pages_app/service_4.jpg' %}" alt="" />
                        </a>
                        <div class="portfolio-caption">
                            <div class="portfolio-caption-heading">قضايا المرأة</div>
                            <div class="portfolio-caption-subheading text-muted">نقدم إستشارات بكل ما يخص المرأة والمجتمع</div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 col-sm-6 mb-4 mb-sm-0 text-center">
                    <div class="portfolio-item">
                        <a class="portfolio-link" data-toggle="modal" href="{% url 'pages_app:under_construction' %}">
                            <div class="portfolio-hover">
                                <div class="portfolio-hover-content"><i class="fab fa-centos fa-3x"></i></div>
                            </div>
                            <img width="100%" class="img-fluid" src="{% static 'images/pages_app/service_5.jpg' %}" alt="" />
                        </a>
                        <div class="portfolio-caption">
                            <div class="portfolio-caption-heading">محكمين دوليين</div>
                            <div class="portfolio-caption-subheading text-muted">خبرة في أنظمة التحكيم الدولية المعتمدة</div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 col-sm-6 text-center">
                    <div class="portfolio-item">
                        <a class="portfolio-link" data-toggle="modal" href="{% url 'pages_app:under_construction' %}">
                            <div class="portfolio-hover">
                                <div class="portfolio-hover-content"><i class="fab fa-centos fa-3x"></i></div>
                            </div>
                            <img width="100%" class="img-fluid" src="{% static 'images/pages_app/service_6.jpg' %}" alt="" />
                        </a>
                        <div class="portfolio-caption">
                            <div class="portfolio-caption-heading">النزاعات الشخصية</div>
                            <div class="portfolio-caption-subheading text-muted">فريق متخصص للإستشارات في حل النزاعات</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>




    <!-- Team-->
    <section class="page-section" id="team">
        <div class="container">
            <div class="text-center">
                <h2 class="section-heading text-uppercase">المحامون</h2>
                <h3 class="section-subheading text-muted">لدينا نخبة مميزة من الخبراء القانونيين والمحاميين الأكفاء.</h3>
            </div>
            <div class="row">
                <div class="col-lg-4">
                    <div class="team-member">
                        <img class="mx-auto rounded-circle" src="{% static 'images/pages_app/p_1.png' %}" alt="" />
                        <h4>المحامي فلان الفلاني</h4>
                        <p class="text-muted">
                            إستشاري القضايا التجارية إستشاري القضايا التجارية إستشاري القضايا التجارية إستشاري القضايا التجارية إستشاري القضايا التجارية إستشاري القضايا التجارية
                        </p>
                        <a class="btn btn-dark btn-social mx-2" href="#!"><i class="fab fa-twitter"></i></a>
                        <a class="btn btn-dark btn-social mx-2" href="#!"><i class="fab fa-facebook-f"></i></a>
                        <a class="btn btn-dark btn-social mx-2" href="#!"><i class="fab fa-linkedin-in"></i></a>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="team-member">
                        <img class="mx-auto rounded-circle" src="{% static 'images/pages_app/p_2.png' %}" alt="" />
                        <h4>المحامي فلان الفلاني</h4>
                        <p class="text-muted">
                            مدير المؤسسة مدير المؤسسة مدير المؤسسة مدير المؤسسة مدير المؤسسة مدير المؤسسة مدير المؤسسة
                        </p>
                        <a class="btn btn-dark btn-social mx-2" href="#!"><i class="fab fa-twitter"></i></a>
                        <a class="btn btn-dark btn-social mx-2" href="#!"><i class="fab fa-facebook-f"></i></a>
                        <a class="btn btn-dark btn-social mx-2" href="#!"><i class="fab fa-linkedin-in"></i></a>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="team-member">
                        <img class="mx-auto rounded-circle" src="{% static 'images/pages_app/p_3.png' %}" alt="" />
                        <h4>المحامي فلان الفلاني</h4>
                        <p class="text-muted">
                            إستشاري القضايا الإجتماعية إستشاري القضايا الإجتماعية إستشاري القضايا الإجتماعية إستشاري القضايا الإجتماعية إستشاري القضايا الإجتماعية
                        </p>
                        <a class="btn btn-dark btn-social mx-2" href="#!"><i class="fab fa-twitter"></i></a>
                        <a class="btn btn-dark btn-social mx-2" href="#!"><i class="fab fa-facebook-f"></i></a>
                        <a class="btn btn-dark btn-social mx-2" href="#!"><i class="fab fa-linkedin-in"></i></a>
                    </div>
                </div>
            </div>
        </div>
    </section>






    <section id="sites_links">
        <div class="container-fluid bg-dark pb-3">
            <span>
                <h5 class="text-center text-muted pt-2 ">مواقع تهمك</h5>
            </pan>
            <div class="row bg-dark text-center">
                <div class="col-lg-2  col-md-4 col-sm-6">
                    <a href="https://www.absher.sa/portal/landing.html "><img class="myimg-size img-responsive" src="{% static 'images/pages_app/site_1.jpg' %}" /></a>
                </div>
                <div class="col-lg-2  col-md-4 col-sm-6">
                    <a href="https://najiz.moj.gov.sa/Account/Login?ReturnUrl=%2FHome%2FDashboard"><img class="myimg-size img-responsive" src="{% static 'images/pages_app/site_2.jpg' %}" /></a>
                </div>
                <div class="col-lg-2  col-md-4 col-sm-6">
                    <a href="https://www.my.gov.sa/wps/portal/snp/pages/agencies/agencyDetails/AC057"><img class="myimg-size img-responsive" src="{% static 'images/pages_app/site_3.png' %}" /></a>
                </div>
                <div class="col-lg-2  col-md-4 col-sm-6">
                    <a href="https://www.moj.gov.sa/ar/pages/default.aspx"><img class="myimg-size img-responsive" src="{% static 'images/pages_app/site_4.jpg' %}" /></a>
                </div>
                <div class="col-lg-2  col-md-4 col-sm-6">
                    <a href="#"><img class="myimg-size img-responsive" src="{% static 'images/pages_app/site_5.jpg' %}" /></a>
                </div>
                <div class="col-lg-2  col-md-4 col-sm-6">
                    <a href="#"><img class="myimg-size img-responsive" src="{% static 'images/pages_app/site_4.jpg' %}" /></a>
                </div>
            </div>
        </div>
    </section>



</div>
{% endblock content%}

pages_app/templates/pages_app/success_contactus.html
{% extends 'base.html' %} {% block content %}

<br><br><br><br><br><br>

<div class="container">
    <section>
        <div>

        </div>


    <!--messges -->
    {% if messages %} {% for message in messages %}
    <div class='alert alert-{{message.tags}}'>
        <strong>{{ message }}</strong>
    </div> {% endfor %} {% endif %}
    <!--end messages -->

        <!-- contact us by email form  -->
        <div class='row' style="background-color: cornsilk; padding:10px;margin-bottom:20px; ">

            <div class='col-md-6'>
                <h3> Success Cotact us</h3> 
            </div>

            <div class="col-md-6 wow fadeInLeft " style='padding:70px;'>
                <i class="fa fa-mobile-phone " aria-hidden="true "></i>
            </div>
        
        
        </div>
    <br><br><br>
    </section>
</div>


{% endblock %}