blog_app/urls.py
from django.urls import path
from .import views


app_name = 'blog_app'
urlpatterns =[
    path('cats_list/', views.cats_list, name='cats_list'),
    path('posts_to_cat/<int:cat_id>/', views.posts_to_cat, name='posts_to_cat'),
    path('posts_to_cat/<int:cat_id>/post_add/',views.post_add, name='post_add'),  
    path('posts_to_cat/<int:cat_id>/post_detail/<int:post_id>/',views.cat_post_detail, name='cat_post_detail'),
    path('posts_to_cat/<int:cat_id>/post_detail/<int:post_id>/update/',views.post_update, name='post_update'),
    path('posts_to_cat/<int:cat_id>/post_detail/<int:post_id>/delete-confirm/',views.post_delete_confirm, name='post_delete_confirm'),
    path('posts_to_cat/<int:cat_id>/post_detail/<int:post_id>/delete/',views.post_delete, name='post_delete'),

    #path('cat_add/', views.cats_add, name='cat_add'),#not need
    # path('cat_detail/<slug:cat_id>/', views.cat_detail, name='cat_detail'), #not need
    # path('all_posts_list/', views.all_posts_list, name='all_posts_list'),#not need
]

site_proj/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('pages_app.urls')),
    path('', include('blog_app.urls')),
    path('',include('account_app.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
# Create your models here.

# --------category model ------#
class Category(models.Model):
    cat_title = models.CharField(
        max_length=255,
        verbose_name='Category Title',
        help_text="create unique title for the Category 'Max Length: 255'",
        unique=True,
        null=True,
        blank=False)

    cat_des = models.CharField(
        max_length=255,
        verbose_name='Category Description',
        help_text=" create short descirption about this Category 'Max Length: 255'",
        unique=False,
        null=True,
        blank=False)

    cat_created = models.DateTimeField(
        verbose_name='Category Created Date',
        auto_now_add=True,
        auto_now=False,
        null=True)

    cat_updated = models.DateTimeField(
        verbose_name='Category Updated Date',
        auto_now_add=False,
        auto_now=True,
        null=True)

    cat_image = models.ImageField(
        verbose_name='Category Image',
        help_text=' create Category Image',
        upload_to='cats_images/%Y/%m/%d/',
        default='default.jpg',
        null = True)

    class Meta:
        ordering = ('-cat_created',)
    
    

    #  counter of posts belong to this category 
    def posts_for_cat_count(self):
        return Post.objects.all().filter(cat_fk=self.id).count()


    def __str__(self):
        return self.cat_title


    # def get_absolute_url(self):
    #     return reverse('blog_app:cat_detail', args=[str(self.id)])




# ------ Post model ---------------------#
class Post(models.Model):
    cat_fk = models.ForeignKey(
        Category,
        verbose_name='Category FK',
        on_delete=models.CASCADE,
        related_name='posts_to_cat')
    
    # must name be --- user_fk
    post_author = models.ForeignKey(
        User,
        verbose_name='Post author',
        on_delete=models.CASCADE,
        related_name='posts_to_author')

   
    post_title = models.CharField(
        verbose_name='Post subject',
        max_length=255,
        unique=True,
        help_text="create unique subject of your post 'Max Length: 255'",
        blank=False,
        null=True)
    
    post_text = models.TextField(
        verbose_name='Post text',
        max_length=4000,
        unique=False,
        help_text="createyour post 'Max Length: 4000'",
        blank=False,
        null=True)

    
    post_created = models.DateTimeField(
        verbose_name='Post Created Date',
        auto_now_add=True,
        auto_now=False,
        null=True)

    post_updated = models.DateTimeField(
        verbose_name='Post Updated Date',
        auto_now_add=False,
        auto_now=True,
        null=True)

    post_views_counter = models.PositiveIntegerField(default=0)
    
    
    # post_like = models.ManyToManyField(
    #     User,
    #     blank=True)

   

    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )

    post_status = models.CharField(
        max_length=10,
        choices=STATUS_CHOICES,
        default='published')


    class Meta:
      ordering = ('-post_created',)
    
    def __str__(self):
        return self.post_title


    #  get number of comments belong to each post
    def comments_for_post_count(self):
        return Comment.objects.all().filter(post_fk=self.id).count()
    



    # get author name belong each post: --- not good to use__ not need :(
    # def author_for_each_post(self):
    #     return User.objects.all().filter(username=self.post_author)


    def get_absolute_url(self):
      return reverse('blog_app:post_detail', args=[str(self.id)])








# ------------------Comment model ----------#
class Comment(models.Model):
    post_fk = models.ForeignKey(
        Post,
        verbose_name='تابع للموضوع',
        on_delete=models.CASCADE,
        related_name='comments_to_post')

    comment_author = models.ForeignKey(
        User,
        verbose_name='كاتب التعليق',
        on_delete=models.CASCADE,
        related_name='Comments_to_author')


    comment_text = models.TextField(
        verbose_name='نص التعليق',
        max_length=4000,
        unique=False,
        help_text="يجب أن لا يتجاوز طول النص 4000",
        blank=False,
        null=True)


    comment_created = models.DateTimeField(
        verbose_name='تاريخ النشر',
        auto_now_add=True,
        auto_now=False,
        null=True)


    comment_updated = models.DateTimeField(
        verbose_name='تاريخ التعديل',
        auto_now_add=False,
        auto_now=True,
        null=True)


    # comments_views_counter = models.PositiveIntegerField(default=0)


    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    comment_status = models.CharField(
        max_length=10,
        choices=STATUS_CHOICES,
        default='published')

    class Meta:
      ordering = ('-comment_created',)

    def __str__(self):
        return self.comment_text





    # comment_like = models.ManyToManyField( -- not work !!
        #     User,
        #     blank=True)



    

    #  add a new comment counter belong to this post
    # def add_comment_counter(self):
    #     number_of_comments=Comment.objects.all().count()
    #     add_comment_count = number_of_comments+1
    #     return add_comment_count

blog_app/forms.py
from .models import Comment,Post
from django import forms



# ----- add post form --------#
class PostForm(forms.ModelForm):
    post_title = forms.CharField(label='عنوان الموضوع', max_length=100,required=True, disabled=False)
    post_text = forms.CharField(label='نص الموضوع',
                                max_length=4000,
                                help_text='يجب أن لا يتجاوز طول النص 4000 ',
                                widget = forms.Textarea(attrs={'placeholder': ' إكتب موضوعك هنا .. '}))
    class Meta:
        model = Post
        fields = ('post_title', 'post_text')




# ----- add comment form --------#
class CommentForm(forms.ModelForm):
    comment_text = forms.CharField(label='نص التعليق',
                                max_length=4000,
                                help_text='يجب أن لا يتجاوز طول التعليق 4000',
                                widget=forms.Textarea(
                                    attrs={'placeholder': 'ضع تعليقك هنا'}))
    class Meta:
        model = Comment
        fields = ['comment_text']

blog_app/views.py
from django.contrib import messages
from django.shortcuts import render, get_object_or_404, redirect
from .models import Category, Post, Comment
from .forms import PostForm, CommentForm
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage


# ------------category------------------------------------------------------#
def cats_list(request):
    page_title = 'الأقسام الرئيسية'
    cats = Category.objects.all()
    #-- counter of categories --#
    cats_count = Category.objects.all().count()
    
    #-- paginator --#
    paginator = Paginator(cats, 5)
    page = request.GET.get('page')
    try:
        cats = paginator.page(page)
    except PageNotAnInteger:
        cats = paginator.page(1)
    except EmptyPage:
        cats = paginator.page(paginator.num_page)
    
    context = {
        'page' : page ,
        'page_title': page_title,
        'cats':cats,
        'cats_count': cats_count,
    }
    return render(request, 'blog_app/cats_list.html', context)



# ----------- same as cat dtail (need 1 args)--------------#
def posts_to_cat(request,cat_id):
    page_title = 'Posts to selected category'
    cat_selected = get_object_or_404(Category, id=cat_id)
    posts_cat = Post.objects.all().filter(cat_fk=cat_id)
    posts_cat_count = Post.objects.all().filter(cat_fk=cat_id).count() 
    
    #-- paginator --#
    paginator = Paginator(posts_cat, 3)
    page = request.GET.get('page')
    try:
        posts_cat = paginator.page(page)
    except PageNotAnInteger:
        posts_cat = paginator.page(1)
    except EmptyPage:
        posts_cat = paginator.page(paginator.num_page)

    
    context = {
        'page': page ,     
        'cat_selected': cat_selected,
        'posts_cat': posts_cat,
        'posts_cat_count': posts_cat_count,
        'page_title': page_title,
    }
    return render(request, 'blog_app/posts_to_category.html', context)



# ------------------need 2 args---------#
@login_required(login_url='account_app:login')

def cat_post_detail(request, cat_id, post_id):
    cat_selected = get_object_or_404(Category, id=cat_id)
    posts_cat = Post.objects.all().filter(cat_fk=cat_id)
    cat_post_detail = get_object_or_404(Post, cat_fk=cat_id, id=post_id, post_status='published')
   
    # to get views counter for selected post 
    session_key ='view_status_post_{}'.format(cat_post_detail.id)
    if not request.session.get(session_key,False):
       cat_post_detail.post_views_counter = cat_post_detail.post_views_counter+1
       cat_post_detail.save()
       request.session[session_key]=True


    #---to show comments for this post
    comments = Comment.objects.all().filter(post_fk= post_id)
    comments_post_count = Comment.objects.all().filter(post_fk=post_id).count()


    #---to show add comment form for this post -----#
    if request.method == "POST":
        comment_form = CommentForm(data=request.POST)
        
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.post_fk = cat_post_detail
            new_comment.comment_author = request.user
            new_comment.save()
            comment_form = CommentForm()
            messages.success(request,f'شكراً  ( {request.user.username} ),  تم إضافة تعليقك بنجاح ')
            return redirect('blog_app:cat_post_detail', cat_id=cat_selected.id, post_id=cat_post_detail.id)
           

            # #---- to get comments counter for this post
            # comments = Comment.objects.all().filter(post_fk= post_id)
            # comments_post_count = Comment.objects.all().filter(post_fk=post_id).count()        
    else:
        comment_form = CommentForm()
        
    context ={
        'cat_selected': cat_selected,
        'cat_post_detail': cat_post_detail,
        'comments': comments,
        'form': comment_form,
        'comments_post_count': comments_post_count,   
    }
    return render(request, 'blog_app/cat_post_detail.html', context)



# -------------------------------------------#
@login_required(login_url='account_app:login')

def post_add(request,cat_id):
    cat_selected = get_object_or_404(Category, id=cat_id)
    
    # --- to get posts counter for this category 
    posts_cat = Post.objects.all().filter(cat_fk=cat_id)
    posts_cat_count = Post.objects.all().filter(cat_fk=cat_id).count()
    
    # -- add new post form 
    if request.method=='POST':
        post_form = PostForm(request.POST)
        if post_form.is_valid():
            new_post = post_form.save(commit=False)
            new_post.cat_fk = cat_selected
            new_post.post_author = request.user
            new_post.save()
            post_form = PostForm()
            messages.success(
            request, f'شكراً  ( {request.user.username} ),تم إضافة الموضوع الجديد بنجاح')
            return redirect('blog_app:posts_to_cat', cat_id=cat_selected.id)
    else:
        post_form = PostForm()
    context = {
        'cat_selected': cat_selected,
        'posts_cat_count' : posts_cat_count ,
        'form' : post_form,

    }
    return render(request, 'blog_app/post_add.html', context)
# -------------------------#


#--- post update -----------#
@login_required(login_url='account_app:login')

def post_update(request, cat_id, post_id):
    cat_selected = get_object_or_404(Category, id=cat_id)
    posts_cat = Post.objects.all().filter(cat_fk=cat_id)
    cat_post_detail = get_object_or_404(Post, cat_fk=cat_id, id=post_id, post_status='published')
    
    post_form = PostForm(request.POST or None,
                         request.FILES or None,
                         instance=cat_post_detail)
    if post_form.is_valid():
        new_post= post_form.save(commit=False)
        new_post.cat_fk = cat_selected
        new_post.post_author = request.user
        new_post.save()
        messages.success(request, f'شكراً  ( {request.user.username} ),تم التعديل بنجاح')
        return redirect('blog_app:cat_post_detail', cat_id=cat_selected.id, post_id=cat_post_detail.id)
    
    context ={
        'form' : post_form,
        'cat_selected': cat_selected,
        'cat_post_detail': cat_post_detail,
    }
    return render(request, 'blog_app/post_update.html', context)



#--- post delete_confirm -----------#
@login_required(login_url='account_app:login')

def post_delete_confirm(request, cat_id, post_id):
    cat_selected = get_object_or_404(Category, id=cat_id)
    posts_cat = Post.objects.all().filter(cat_fk=cat_id)
    cat_post_detail = get_object_or_404(Post, cat_fk=cat_id, id=post_id, post_status='published')
    print(cat_post_detail)
    if request.method =='POST':
        print('POST')
        cat_post_detail.delete()
        
        messages.success(request, f'شكراً ( {request.user.username} ), تم حذف موضوعك ')
        return redirect('blog_app:posts_to_cat', cat_id=cat_selected.id)

    context ={
        'cat_selected': cat_selected,
        'cat_post_detail': cat_post_detail,
    }
    return render(request,'blog_app/post_delete_confirm.html',context)







#--- post delete -----------#
@login_required(login_url='account_app:login')

def post_delete(request, cat_id, post_id):
    cat_selected = get_object_or_404(Category, id=cat_id)
    posts_cat = Post.objects.all().filter(cat_fk=cat_id)
    cat_post_detail = get_object_or_404(Post, cat_fk=cat_id, id=post_id, post_status='published')
    print(cat_post_detail)
    
    cat_post_detail.delete()
    
    messages.success(request, f'شكراً ( {request.user.username} ), تم حذف موضوعك ')
    return redirect('blog_app:posts_to_cat', cat_id=cat_selected.id)

    

blog_app/templates/blog_app/cat_post_detail.html
{% extends 'base.html' %}{% load crispy_forms_tags %}{% block content %}
<!--messges start -->
<section id="messages">
    <div class="container">
        {% if messages %} {% for message in messages %}
        <br><br><br><br><br><br>
        <div class='alert alert-{{message.tags}}'>
            <strong class="text-center">{{ message }}</strong>
        </div> {% endfor %} {% endif %}
    </div>
</section>
<!-- messages end -->


<!-- breadcrumb start -->
<section id="mybreadcrumb">
    <div class="container">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a class="stretched-link" href="{% url 'blog_app:cats_list' %}">الأقسام الرئيسية</a></li>
                <li class="breadcrumb-item "><a class="stretched-link" href="{% url 'blog_app:posts_to_cat' cat_selected.id %}">{{cat_selected}}</a></li>
                <li class="breadcrumb-item active" aria-current="page">{{cat_post_detail}}</li>
            </ol>

        </nav>
    </div>
</section>
<!--  end breadcrumb -->



<!-- start padge -->
<section id="padge">
    <div class="container">
        <div class="badge badge-warning float-left">
            <span class="badge badge-light">{{comments_post_count}}</span> تعليق
        </div>
    </div>
</section>
<!-- end padge -->



<!-- start buttons update delete  -->
<section id="updatedeletebt">
    <div class="container">
        {% if cat_post_detail.post_author == user %}
        <div>
            <a class="btn btn-sm btn-danger mr-1  float-right" href="{% url 'blog_app:post_delete_confirm' cat_selected.id  cat_post_detail.id  %}"><i class="far fa-trash-alt"></i></a>
            <a class="btn btn-sm btn-success  mr-1 float-right" href="{% url 'blog_app:post_update' cat_selected.id  cat_post_detail.id  %}"><i class="far fa-edit"></i></a>
        </div>
        {% endif %}
    </div>
</section>
<!-- end buttons update delete  -->



<!-- start post detail -->
<section id="postdetail">
    <div class="container">
        <div class="postcard mt-2">
            <div class="row no-gutters">
                <div class="col-md-2 float-left">
                    <img src="{{cat_post_detail.post_author.profile_to_user.prof_image.url}}" alt="{{cat_post_detail.post_title}}" class="float-left rounded-circle m-1" width="110px" height="110px">
                </div>
                <div class="col-md-10">
                    <div class="card-body">
                        <div>
                            <h4 class="card-title">{{cat_post_detail.post_title}}</h4>
                        </div>
                        <h4>
                            <div class="badge badge-secondary">
                                <span class="badge badge-warning"><i class="fas fa-user-edit"></i></span> {{cat_post_detail.post_author}}
                            </div>
                        </h4>

                        <p class="card-text">
                            {{cat_post_detail.post_text}}
                        </p>

                        <p class="card-text ">
                            <small class="text-muted ">
                                <span style="font-size: 19px;">
                                    <i class="far fa-calendar-check"></i>{{cat_post_detail.post_created |date:'d-m-Y'}}  | 
                                    <i class="far fa-calendar-plus"></i>{{cat_post_detail.post_updated |date:'d-m-Y'}}  |
                                    <i class="fa fa fa-eye"></i>  {{cat_post_detail.post_views_counter}}    | 
                                    <i class="far fa-comments"></i>  {{comments_post_count }}
                                </span>
                            </small>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- end post detil -->



<section>
    <div class="container">
        <h5 class="text-center text-warning mt-2 mb-2">التعليقات({{comments_post_count}})</h5>
    </div>
</section>

<!-- start comments list -->
<section id="commentslist">
    <div class="container">
        {% for comment in comments %}
        <div class="postcard  m-1 border-top-0 border-right-0 border-left-0">
            <div class="row no-gutters">
                <div class="col-md-2">
                    <img src="{{comment.comment_author.profile_to_user.prof_image.url}} " alt="{{comment.comment_author}} " class="image-wrap img-fluid mt-1 ml-1 float-left rounded-circle" width="90px" height="90px">
                </div>
                <div class="col-md-10">
                    <div class="card-body">
                        <div>
                            <h4 class="card-title">{{post.post_title}}</h4>
                        </div>

                        <h5><span class="badge badge-warning"><i class="far fa-comment"></i></span> {{comment.comment_author}} </h5>


                        <p class="card-text text-secondary">
                            {{comment.comment_text}}
                        </p>

                        <p class="card-text ">
                            <small class="text-muted ">
                                <span style="font-size: 19px;">
                                    <i class="far fa-calendar-check"></i>{{comment.comment_created |date:'d-m-Y'}}  | 
                                    <i class="far fa-calendar-plus"></i>{{comment.comment_updated |date:'d-m-Y'}}  |
                                </span>
                            </small>
                        </p>
                    </div>
                </div>
            </div>
        </div>
        {% empty %}
        <div class="card m-1 text-center mb-5 ">
            <div class="card-body ">
                <p class="card-text ">لم يتم إضافة تعليق لهذ الموضوع بعد .</p>
                <span class="ml-auto ">
                     كن أول من يضع تعليق لهذا الموضوع من  
                         <a href="#">
                               هنا 
                         </a>
                    </span>
            </div>
        </div>
        {% endfor %}
    </div>
</section>
<!-- end comments list -->


<!--start add comment form -->
<section>
    <div class="container">
        <div class="row">
            <div class="col-md-10">
                <div class="text-center">
                    <form method="POST" class="form-group" enctype="multipart/form-data">

                        {% csrf_token %}

                        <div class="form-group">
                            {{form.comment_text|as_crispy_field}}
                        </div>

                        <button type="submit" class="btn btn-sm btn-warning mb-5">إضافة</button>

                    </form>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- end add comment form-->

{% endblock %}

blog_app/templates/blog_app/post_delete.html
 {% extends 'base.html' %}{% load crispy_forms_tags %}{% block content %}
<!--messges start -->
<section id="messages">
    <div class="container">
        {% if messages %} {% for message in messages %}
        <div class='alert alert-{{message.tags}}'>
            <strong>{{ message }}</strong>
        </div> {% endfor %} {% endif %}
    </div>
</section>
<!-- messages end -->


<!-- breadcrumb start -->
<section id="mybreadcrumb">
    <div class="container">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a class="stretched-link" href="{% url 'blog_app:cats_list' %}">الأقسام الرئيسية</a></li>
                <li class="breadcrumb-item "><a class="stretched-link" href="{% url 'blog_app:posts_to_cat' cat_selected.id %}">{{cat_selected}}</a></li>
                <li class="breadcrumb-item active" aria-current="page">{{cat_post_detail}}</li>
            </ol>

        </nav>
    </div>
</section>
<!--  end breadcrumb -->



<section>
    <div class="container">
        <strong><p class="text-secondary text-center mb-2">حذف الموضوع</p></strong>
    </div>
</section>






<!-- start delete post form  -->
<section>
    <div class="container">
        <div class="row">
            <div class="col-md-10">
                <div class="text-center">
                    <form method="POST" action="{% url 'blog_app:post_delete' cat_id=cat_selected.id   post_id=cat_post_detail.id %}" enctype="multipart/form-data">

                        {% csrf_token %}


                        <div class="border mt-3 mb-3">
                            <p>هل أنت متأكد أنك تريد حذف الموضوع :</p>
                            <h5>{{cat_post_detail}}</h5>
                        </div>


                        <div class="mb-3">
                            <span>
                            <a class="stretched-link" href="{% url 'blog_app:cat_post_detail' cat_selected.id  cat_post_detail.id  %}">إلغاء</a>
                        </span>
                            <span>
                            <button type="submit" class="btn btn-sm btn-danger  text-right">حذف</button>
                        </span>
                        </div>


                    </form>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- end delete post  -->
{% endblock %}

blog_app/templates/blog_app/post_delete_confirm.html
 {% extends 'base.html' %}{% load crispy_forms_tags %}{% block content %}
<!--messges start -->
<section id="messages">
    <div class="container">
        {% if messages %} {% for message in messages %}
        <div class='alert alert-{{message.tags}}'>
            <strong class="text-center">{{ message }}</strong>
        </div> {% endfor %} {% endif %}
    </div>
</section>
<!-- messages end -->


<!-- breadcrumb start -->
<section id="mybreadcrumb">
    <div class="container">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a class="stretched-link" href="{% url 'blog_app:cats_list' %}">الأقسام الرئيسية</a></li>
                <li class="breadcrumb-item "><a class="stretched-link" href="{% url 'blog_app:posts_to_cat' cat_selected.id %}">{{cat_selected}}</a></li>
                <li class="breadcrumb-item active" aria-current="page">{{cat_post_detail}}</li>
            </ol>

        </nav>
    </div>
</section>
<!--  end breadcrumb -->




<!-- start delete post form  -->
<section>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="text-center">
                    <form method="POST" action="{% url 'blog_app:post_delete' cat_id=cat_selected.id   post_id=cat_post_detail.id %}" enctype="multipart/form-data">

                        {% csrf_token %}


                        <div class="border mt-3 mb-3 bg-primary">
                            <p>هل أنت متأكد أنك تريد حذف الموضوع :</p>
                            <h5>{{cat_post_detail}}</h5>
                            <br>
                                <a href="{% url 'blog_app:cat_post_detail' cat_selected.id  cat_post_detail.id  %}" class="btn btn-sm btn-secondary">إلغاء</a>
                                <a  href="{% url 'blog_app:post_delete' cat_selected.id  cat_post_detail.id  %}" class="btn btn-sm btn-danger  text-right">حذف</a>
                            <br> <br>
                        </div>


                    </form>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- end delete post  -->
{% endblock %}

blog_app/templates/blog_app/posts_to_category.html
{% extends 'base.html' %} {% block content %}


<!--messges start -->
<section id="messages">
    <div class="container">
        {% if messages %} {% for message in messages %}
        <div class='alert alert-{{message.tags}}'>
            <strong class="text-center">{{ message }}</strong>
        </div> {% endfor %} {% endif %}
    </div>
</section>
<!-- messages end -->



<section id="mybreadcrumb">
    <div class="container">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a class="stretched-link" href="{% url 'blog_app:cats_list' %}">الأقسام الرئيسية</a></li>
                <li class="breadcrumb-item active" aria-current="page">{{cat_selected.cat_title}}</li>
            </ol>

        </nav>
    </div>
</section>



<section id="padge_add">
    <div class="container">
        <div class="badge badge-warning float-left">
            <span class="badge badge-light">{{posts_cat_count}}</span> موضوع
        </div>

<br><br>

        <div class="float-right">
            <a href="{% url  'blog_app:post_add'  cat_selected.id %}" class="btn btn-sm btn-outline-warning">
                <i class="fas fa-plus-circle fa-1x"></i> موضوع جديد
            </a>
        </div>
    </div>
</section>


<section id="pagination">
    <div class="container">
        {% include 'blog_app/pagination.html' with page=posts_cat %}
    </div>
</section>


<section id="postscat">
    <div class="container">
        {% for post in posts_cat %}
        <div class="postcard mb-3 border-top-0 border-right-0 border-left-0">
            <div class="row no-gutters">
                <div class="col-md-2 pt-4">
                    <img src="{{post.post_author.profile_to_user.prof_image.url}}" alt=" {{post.post_author}}" class="image-wrap img-fluid mt-1 ml-1 float-left rounded-circle" width="110px" height="110px">
                </div>
                <div class="col-md-10">
                    <div class="card-body">
                        <div>
                            <a href="{% url 'blog_app:cat_post_detail' cat_selected.id post.id %}">
                                <h4 class="card-title">{{post.post_title}}</h4>
                            </a>
                        </div>

                        <h4>
                            <div class="badge badge-secondary">
                                <span class="badge badge-warning"><i class="fas fa-user-edit"></i></span> {{post.post_author}}
                            </div>
                        </h4>



                        <p class="card-text ">
                            {% if post.post_text|length > 200 %} {{post.post_text|slice:'210'}} ..
                            <a href="{% url 'blog_app:cat_post_detail' cat_selected.id post.id %}"> 
                                 المزيد 
                                </a> {% else %} {{post.post_text}} {% endif %}
                        </p>
                        <p class="card-text ">
                            <small class="text-muted ">
                                <span style="font-size: 19px;">
                                    <i class="far fa-calendar-check"></i></i> {{post.post_created |date:'d-m-Y'}}  | 
                                    <i class="far fa-calendar-plus "></i></i> {{post.post_updated |date:'d-m-Y'}}  |
                                    <i class="fa fa fa-eye "></i> {{post.post_views_counter}}  | 
                                    <i class="far fa-comments"></i> {{post.comments_for_post_count}}
                                </span>
                            </small>
                        </p>
                    </div>
                </div>
            </div>
        </div>
        {% empty %}
        <div class="card text-center mb-5 ">
            <div class="card-body ">
                <p class="card-text ">لم يتم إضافة مواضيع لهذ القسم بعد .</p>
                <span class="ml-auto ">
                     كن أول من يضع موضوع لهذا القسم من  
                         <a href="{% url 'blog_app:post_add' cat_selected.id %} ">
                               هنا 
                         </a>
                    </span>
            </div>
        </div>
        {% endfor %}

    </div>
</section>


<section id="pagination">
    <div class="container">
        {% include 'blog_app/pagination.html' with page=posts_cat %}
    </div>
</section>

{% endblock %}